# ----------------------------------------------------------------------------
#  File:        prometheus.yml
#  Project:     Celaya Solutions (C-Suite Blockchain)
#  Created by:  Celaya Solutions, 2025
#  Author:      Christopher Celaya <chris@celayasolutions.com>
#  Description: Prometheus configuration for blockchain metrics collection
#  Version:     1.0.0
#  License:     BSL (SPDX id BUSL)
#  Last Update: (June 2025)
# ----------------------------------------------------------------------------

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'celaya-testnet'
    environment: 'development'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Substrate node metrics
  - job_name: 'substrate-node'
    static_configs:
      - targets: ['host.docker.internal:9615']
    scrape_interval: 10s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # Vector metrics
  - job_name: 'vector'
    static_configs:
      - targets: ['vector:9598', 'vector:9599']
    scrape_interval: 15s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: /metrics

  # Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
    metrics_path: /metrics

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: /metrics

  # System metrics (if node_exporter is running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s 