[settings]
timeout = 1000
provider = "native"

[relaychain]
default_image = "polkadot:latest"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000

  [parachains.collator]
  name = "collator01"
  command = "parachain-template-node"
  args = [ "-lparachain=debug" ]
